/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package biblioMVC2;

import biblioMVC2.database.Conexao;
import biblioMVC2.view.TelaLogin;

public class App {
    public static void main(String[] args) {
        new TelaLogin().setVisible(true);
    }
}
