/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PokeList;

import javax.swing.DefaultListModel;

/**
 *
 * @author GUSTAVOHENRIQUEDEOLI
 */
public class ComputadorPokemon extends javax.swing.JFrame {

    /**
     * Creates new form ComputadorPokemon
     */
    
    private DefaultListModel<String> modeloLista;
    
    public ComputadorPokemon() {
        initComponents();
        modeloLista = new DefaultListModel<>();
        ListaPokemonComputador.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaComputador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPokemonComputador = new javax.swing.JList<>();
        btnCompPmochila = new javax.swing.JButton();
        IndicadorComputador = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaPokemonMochila = new javax.swing.JList<>();
        IndicadorMochila = new javax.swing.JLabel();
        btnMochilaPcomp = new javax.swing.JButton();
        txtAnuncios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        TelaComputador.setBackground(new java.awt.Color(255, 102, 0));

        ListaPokemonComputador.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista_Vazia" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaPokemonComputador);

        btnCompPmochila.setText("Para a mochila");
        btnCompPmochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompPmochilaActionPerformed(evt);
            }
        });

        IndicadorComputador.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        IndicadorComputador.setText("Computador");

        jScrollPane3.setViewportView(ListaPokemonMochila);

        IndicadorMochila.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        IndicadorMochila.setText("Mochila");

        btnMochilaPcomp.setText("Para o computador");
        btnMochilaPcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMochilaPcompActionPerformed(evt);
            }
        });

        txtAnuncios.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtAnuncios.setText("Gerencionamento de Pokemon");

        javax.swing.GroupLayout TelaComputadorLayout = new javax.swing.GroupLayout(TelaComputador);
        TelaComputador.setLayout(TelaComputadorLayout);
        TelaComputadorLayout.setHorizontalGroup(
            TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaComputadorLayout.createSequentialGroup()
                .addGroup(TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaComputadorLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMochilaPcomp)
                            .addComponent(IndicadorMochila))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TelaComputadorLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaComputadorLayout.createSequentialGroup()
                                .addComponent(txtAnuncios)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(TelaComputadorLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TelaComputadorLayout.createSequentialGroup()
                                        .addGap(0, 10, Short.MAX_VALUE)
                                        .addComponent(btnCompPmochila))
                                    .addGroup(TelaComputadorLayout.createSequentialGroup()
                                        .addComponent(IndicadorComputador)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        TelaComputadorLayout.setVerticalGroup(
            TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaComputadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaComputadorLayout.createSequentialGroup()
                        .addComponent(IndicadorComputador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompPmochila)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnuncios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TelaComputadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaComputadorLayout.createSequentialGroup()
                        .addComponent(btnMochilaPcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IndicadorMochila))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaComputador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaComputador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompPmochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompPmochilaActionPerformed
        int index = ListaPokemonComputador.getSelectedIndex();
        if (index != -1) { // Verifica se algo foi selecionado
            
            modeloLista.remove(index);
        }
    }//GEN-LAST:event_btnCompPmochilaActionPerformed

    private void btnMochilaPcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMochilaPcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMochilaPcompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputadorPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputadorPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputadorPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputadorPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputadorPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IndicadorComputador;
    private javax.swing.JLabel IndicadorMochila;
    private javax.swing.JList<String> ListaPokemonComputador;
    private javax.swing.JList<String> ListaPokemonMochila;
    private javax.swing.JPanel TelaComputador;
    private javax.swing.JButton btnCompPmochila;
    private javax.swing.JButton btnMochilaPcomp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel txtAnuncios;
    // End of variables declaration//GEN-END:variables
}
